version: '3.8'

services:
  jrtb-db:
    image: mysql:8
    container_name: javarush-telegrambot-jrtb-dev-db
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'tgbotuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'tgbotuser'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'tgbot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'